# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffaafd9af85c8c85f72a8661d7542ef1ab952f396c54b549a8f8d6c8a3a7cf7092cb6fb9799b3afa17a14eb0ba7bd85bb658123f3968c8e7171a7d745d2f9547

test:
  secret_key_base: 0bd7a648449be9edf9b82cf2cc740cd87ad8eddcf2bf62dc1d3b6baf7d23266325a1f220011c10f871392d112ebd5d514d2590ead19f7d65e7f29c65ad971771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
